# Generated by Django 4.2.5 on 2023-09-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A', '0002_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
